# Copyright 2015, Hewlett-Packard Development Company, L.P.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# The slug of the dashboard to be added to HORIZON['dashboards']. Required.
DASHBOARD = 'project'
# If set to True, this dashboard will be set as the default dashboard.
DEFAULT = True
# A list of applications to be added to INSTALLED_APPS.
ADD_INSTALLED_APPS = ['easystack_dashboard.dashboards.project']
ADD_ANGULAR_MODULES = ['hz.dashboard',
                       'hz.dashboard.project',
                       'hz.dashboard.project.overview', ]

AWS_LAUNCH_INST = 'dashboard/aws-launch-instance/'
LAUNCH_INST = 'dashboard/launch-instance/'
BAREMETAL_LAUNCH_INST = 'dashboard/baremetal-launch-instance/'

ADD_JS_SPEC_FILES = ['dashboard/workflow/workflow.module.spec.js',
                     'dashboard/cloud-services/cloud-services.spec.js',
                     LAUNCH_INST + 'launch-instance.spec.js',
                     LAUNCH_INST + 'launch-instance.model.spec.js',
                     LAUNCH_INST + 'source/source.spec.js',
                     LAUNCH_INST + 'flavor/flavor.spec.js',
                     LAUNCH_INST + 'network/network.spec.js',
                     LAUNCH_INST + 'security-groups/security-groups.spec.js',
                     LAUNCH_INST + 'keypair/keypair.spec.js',
                     LAUNCH_INST + 'configuration/configuration.spec.js',

                     AWS_LAUNCH_INST + 'launch-instance.spec.js',
                     AWS_LAUNCH_INST + 'launch-instance.model.spec.js',
                     AWS_LAUNCH_INST + 'source/source.spec.js',
                     AWS_LAUNCH_INST + 'flavor/flavor.spec.js',
                     AWS_LAUNCH_INST + 'configuration/configuration.spec.js', ]

ADD_JS_FILES = ['dashboard/dashboard.module.js',
                'dashboard/project/project.module.js',
                'dashboard/workflow/workflow.module.js',
                'dashboard/workflow/decorator.service.js',
                'dashboard/workflow/workflow.service.js',
                'dashboard/tech-debt/tech-debt.module.js',
                'dashboard/tech-debt/namespace-ctrl.js',
                'dashboard/tech-debt/image-form-ctrl.js',
                'dashboard/cloud-services/cloud-services.js',
                'dashboard/project/alarms/alarms.js',
                'dashboard/project/alarms/form.js',
                'dashboard/project/alarms/table.js',
                'dashboard/project/alarms/action.create.js',
                'dashboard/project/alarms/action.delete.js',
                'dashboard/project/alarms/action.edit.js',
                'dashboard/project/alarms/monitor_table.js',
                'dashboard/project/alarms/alarms-directive.js',
                'dashboard/project/alarms/alarms.filter.js',
                'dashboard/project/alarms/action.create.detail.js',
                
                'dashboard/project/easystack_overview/overview.js',
                'dashboard/project/easystack_overview/overview.controller.js',
                'dashboard/project/easystack_overview/overview.service.js',

                'dashboard/project/billing/billing.js',
                'dashboard/project/billing/form.js',
                'dashboard/project/billing/table.controller.js',
                'dashboard/project/billing/table.directive.js',

                'dashboard/project/volumes/volumes.js',
                'dashboard/project/volumes/table.js',
                'dashboard/project/volumes/form.js',
                'dashboard/project/volumes/action.edit.js',
                'dashboard/project/volumes/action.create.js',
                'dashboard/project/volumes/action.delete.js',

                'dashboard/project/volumes/action.snapshot.js',
                'dashboard/project/volumes/action.extend.js',
                'dashboard/project/volumes/action.attach.js',
                'dashboard/project/volumes/action.detach.js',
                'dashboard/project/volumes/action.detail.js',
                'dashboard/project/volumes/action.image.js',

                'dashboard/project/instance_firewall/instance_firewall.js',
                'dashboard/project/instance_firewall/table.js',
                'dashboard/project/instance_firewall/form.js',
                'dashboard/project/instance_firewall/action.create.js',
                'dashboard/project/instance_firewall/action.delete.js',
                'dashboard/project/instance_firewall/action.ruleCreate.js',
                'dashboard/project/instance_firewall/instance_firewall.directive.js',

                'dashboard/project/networks/networks.js',
                'dashboard/project/networks/table.js',
                'dashboard/project/networks/form.js',
                'dashboard/project/networks/action.create.js',
                'dashboard/project/networks/action.delete.js',
                'dashboard/project/networks/action.edit.js',
                'dashboard/project/networks/action.detail.js',
                'dashboard/project/networks/action.directive.js',
                'dashboard/project/networks/detail.js',
                'dashboard/project/networks/network.detail.js',

                'dashboard/project/images/images.js',
                'dashboard/project/images/table.js',
                'dashboard/project/images/form.js',
                'dashboard/project/images/detail.js',
                'dashboard/project/images/action.edit.js',
                'dashboard/project/images/action.create.js',
                'dashboard/project/images/action.delete.js',
                'dashboard/project/images/action.create.detail.js',
                'dashboard/project/images/action.image-create-volume.js',

                'dashboard/project/routers/routers.js',
                'dashboard/project/routers/action.set-gateway.js',
                'dashboard/project/routers/action.unset-gateway.js',
                'dashboard/project/routers/table.js',
                'dashboard/project/routers/form.js',
                'dashboard/project/routers/action.connect.js',
                'dashboard/project/routers/action.disconnect.js',
                'dashboard/project/routers/action.create-rule.js',
                'dashboard/project/routers/action.delete-rule.js',
                'dashboard/project/routers/action.associate-firewall.js',
                'dashboard/project/routers/action.disassociate-firewall.js',

                'dashboard/project/routers/action.edit.js',
                'dashboard/project/routers/action.create.js',
                'dashboard/project/routers/action.delete.js',
                'dashboard/project/routers/action.create.detail.js',
                'dashboard/project/routers/action.remove-rule.js',
                'dashboard/project/routers/action.add-rule.js',

                'dashboard/project/activity/activity.js',
                'dashboard/project/activity/table.js',

                'dashboard/project/keypairs/keypairs.js',
                'dashboard/project/keypairs/table.js',
                'dashboard/project/keypairs/action.create.js',
                'dashboard/project/keypairs/action.import.js',
                'dashboard/project/keypairs/action.delete.js',
                'dashboard/project/keypairs/form.js',

                'dashboard/project/instances/instances.js',
                'dashboard/project/instances/table.js',
                'dashboard/project/instances/monitor.js',
                'dashboard/project/instances/form.js',
                'dashboard/project/instances/action.createsnapshot.js',
                'dashboard/project/instances/action.attach.js',
                'dashboard/project/instances/action.detach.js',
                'dashboard/project/instances/action.associate-floatingip.js',
                'dashboard/project/instances/action.disassociate-floatingip.js',
                'dashboard/project/instances/action.shutoff.js',
                'dashboard/project/instances/action.start.js',
                'dashboard/project/instances/action.softreboot.js',
                'dashboard/project/instances/action.suspend.js',
                'dashboard/project/instances/action.resume.js',
                'dashboard/project/instances/action.pause.js',
                'dashboard/project/instances/action.unpause.js',
                'dashboard/project/instances/action.delete.js',
                'dashboard/project/instances/action.edit.js',
                'dashboard/project/instances/action.detail.js',
                'dashboard/project/instances/action.associate-net.js',
                'dashboard/project/instances/action.disassociate-net.js',
                'dashboard/project/instances/action.monitor.js',
                'dashboard/project/instances/action.securitygroup.js',
                'dashboard/project/instances/action.rebuild.js',
                'dashboard/project/instances/action.resize.js',
                'dashboard/project/instances/action.hotextend.js',
                'dashboard/project/instances/action.memory.js',
                'dashboard/project/instances/total.memory.service.js',
                'dashboard/project/instances/action.novnc.console.js',

                'dashboard/project/floatingIP/floatingIP.js',
                'dashboard/project/floatingIP/table.js',
                'dashboard/project/floatingIP/form.js',
                'dashboard/project/floatingIP/action.allocate.js',
                'dashboard/project/floatingIP/action.release.js',
                'dashboard/project/floatingIP/action.upbandwidth.js',
                'dashboard/project/floatingIP/action.associate-instance.js',
                'dashboard/project/floatingIP/action.disassociate.js',
                'dashboard/project/floatingIP/action.associate-router.js',

                'dashboard/project/instance_snapshots/instance_snapshot.js',
                'dashboard/project/instance_snapshots/action.delete.js',
                'dashboard/project/instance_snapshots/table.js',
                'dashboard/project/instance_snapshots/form.js',
                'dashboard/project/instance_snapshots/action.edit.js',
                'dashboard/project/instance_snapshots/action.createvolume.js',

                'dashboard/project/volume_snapshots/volume_snapshot.js',
                'dashboard/project/volume_snapshots/table.js',
                'dashboard/project/volume_snapshots/form.js',
                'dashboard/project/volume_snapshots/action.delete.js',
                'dashboard/project/volume_snapshots/action.createvolume.js',
                'dashboard/project/volume_snapshots/action.edit.js',

                'dashboard/project/volume_backups/volume_backup.js',
                'dashboard/project/volume_backups/table.js',
                'dashboard/project/volume_backups/form.js',
                'dashboard/project/volume_backups/action.create.js',
                'dashboard/project/volume_backups/action.edit.js',
                'dashboard/project/volume_backups/action.delete.js',

                'dashboard/project/firewalls/firewalls.js',
                'dashboard/project/firewalls/table.js',
                'dashboard/project/firewalls/form.js',
                'dashboard/project/firewalls/policy-table.js',
                'dashboard/project/firewalls/rule-table.js',
                'dashboard/project/firewalls/action.create.js',
                'dashboard/project/firewalls/action.delete.js',
                'dashboard/project/firewalls/action.edit.js',
                'dashboard/project/firewalls/action.create-policy.js',
                'dashboard/project/firewalls/action.delete-policy.js',
                'dashboard/project/firewalls/action.edit-policy.js',
                'dashboard/project/firewalls/action.add-rule-to-policy.js',
                'dashboard/project/firewalls/action.create-rule.js',
                'dashboard/project/firewalls/action.delete-rule.js',
                'dashboard/project/firewalls/action.edit-rule.js',
                'dashboard/project/firewalls/action.associate-router.js',
                'dashboard/project/firewalls/action.disassociate-router.js',

                'dashboard/project/loadbalancersv2/loadbalancersv2.js',
                'dashboard/project/loadbalancersv2/table.js',
                'dashboard/project/loadbalancersv2/loadbalancer/action.associate-floatingip.js',
                'dashboard/project/loadbalancersv2/loadbalancer/action.delete.js',
                'dashboard/project/loadbalancersv2/loadbalancer/action.disassociate-floatingip.js',
                'dashboard/project/loadbalancersv2/loadbalancer/action.edit-securitygroup.js',
                'dashboard/project/loadbalancersv2/loadbalancer/action.create.js',
                'dashboard/project/loadbalancersv2/loadbalancer/action.detail.js',
                'dashboard/project/loadbalancersv2/loadbalancer/form.js',
                'dashboard/project/loadbalancersv2/loadbalancer/detail.controller.js',

                'dashboard/project/loadbalancersv2/loadbalancer/listener/action.create.js',
                'dashboard/project/loadbalancersv2/loadbalancer/listener/action.edit.js',
                'dashboard/project/loadbalancersv2/loadbalancer/listener/form.js',
                'dashboard/project/loadbalancersv2/loadbalancer/listener/action.delete.js',
                'dashboard/project/loadbalancersv2/loadbalancer/listener/action.disable.js',
                'dashboard/project/loadbalancersv2/loadbalancer/listener/action.enable.js',

                'dashboard/project/loadbalancersv2/pool/form.js',
                'dashboard/project/loadbalancersv2/pool/detail.controller.js',
                'dashboard/project/loadbalancersv2/pool/action.create.js',
                'dashboard/project/loadbalancersv2/pool/action.delete.js',
                'dashboard/project/loadbalancersv2/pool/action.edit.js',
                'dashboard/project/loadbalancersv2/pool/action.enable.js',
                'dashboard/project/loadbalancersv2/pool/action.disable.js',
                'dashboard/project/loadbalancersv2/pool/action.detail.js',
                'dashboard/project/loadbalancersv2/pool/member/member-form.js',
                'dashboard/project/loadbalancersv2/pool/member/action.addResources.js',
                'dashboard/project/loadbalancersv2/pool/member/action.deleteMember.js',
                'dashboard/project/loadbalancersv2/pool/member/action.disableMember.js',
                'dashboard/project/loadbalancersv2/pool/member/action.enableMember.js',
                'dashboard/project/loadbalancersv2/pool/member/action.modifyWeight.js',

                'dashboard/project/ports/ports.js',
                'dashboard/project/ports/table.js',
                'dashboard/project/ports/action.create.js',
                'dashboard/project/ports/form.js',
                'dashboard/project/ports/action.attach.js',
                'dashboard/project/ports/action.detach.js',
                'dashboard/project/ports/action.delete.js',
                'dashboard/project/ports/action.edit.js',
                'dashboard/project/ports/action.editSecurityGroup.js',
                'dashboard/project/ports/action.detail.js',

                'dashboard/project/policytargets/policygroup.js',
                'dashboard/project/policytargets/table.js',
                'dashboard/project/policytargets/form.js',
                'dashboard/project/policytargets/action.create.js',
                'dashboard/project/policytargets/action.edit.js',
                'dashboard/project/policytargets/action.detail.js',
                'dashboard/project/policytargets/action.delete.js',

                'dashboard/project/network_policy/network_policy.js',
                'dashboard/project/network_policy/table.js',
                'dashboard/project/network_policy/form.js',
                'dashboard/project/network_policy/nat_pool/action.create.pool.js',
                'dashboard/project/network_policy/nat_pool/action.delete.pool.js',
                'dashboard/project/network_policy/nat_pool/action.edit.pool.js',

                'dashboard/project/network_policy/l3_policy/action.create.l3_policy.js',
                'dashboard/project/network_policy/l3_policy/action.delete.l3_policy.js',
                'dashboard/project/network_policy/l3_policy/action.edit.l3_policy.js',
                'dashboard/project/network_policy/l3_policy/action.add.external_segment_parameter.js',
                'dashboard/project/network_policy/l3_policy/detail.l3_policy.js',

                'dashboard/project/network_policy/l2_policy/action.create.l2_policy.js',
                'dashboard/project/network_policy/l2_policy/action.delete.l2_policy.js',
                'dashboard/project/network_policy/l2_policy/action.edit.l2_policy.js',

                'dashboard/project/network_policy/service_policy/action.create.service_policy.js',
                'dashboard/project/network_policy/service_policy/action.delete.service_policy.js',
                'dashboard/project/network_policy/service_policy/action.edit.service_policy.js',
                'dashboard/project/network_policy/service_policy/action.add.network_service_parameter.js',

                'dashboard/project/network_policy/external_connectivity/action.create.external_connectivity.js',
                'dashboard/project/network_policy/external_connectivity/action.delete.external_connectivity.js',
                'dashboard/project/network_policy/external_connectivity/action.edit.external_connectivity.js',
                'dashboard/project/network_policy/external_connectivity/action.add.external_route_parameter.js',

                'dashboard/project/tickets/tickets.js',
                'dashboard/project/tickets/action.create.js',
                'dashboard/project/tickets/table.js',
                'dashboard/project/tickets/form.js',
                'dashboard/project/tickets/action.detail.js',

                LAUNCH_INST + 'launch-instance.js',
                LAUNCH_INST + 'launch-instance.model.js',
                LAUNCH_INST + 'source/source.controller.js',
                LAUNCH_INST + 'source/source-help.controller.js',
                LAUNCH_INST + 'flavor/flavor.controller.js',
                LAUNCH_INST + 'flavor/select-flavor-table.directive.js',
                LAUNCH_INST + 'flavor/flavor-help.controller.js',
                LAUNCH_INST + 'network/network.controller.js',
                LAUNCH_INST + 'network/network-help.controller.js',
                LAUNCH_INST + 'security-groups/security-groups.js',
                LAUNCH_INST + 'keypair/keypair.js',
                LAUNCH_INST + 'configuration/configuration.controller.js',
                LAUNCH_INST + 'networkports/ports.controller.js',
                LAUNCH_INST + 'networkports/ports-help.controller.js',
    LAUNCH_INST + 'server-groups/server-groups.controller.js',

                AWS_LAUNCH_INST + 'launch-instance.js',
                AWS_LAUNCH_INST + 'launch-instance.model.js',
                AWS_LAUNCH_INST + 'source/source.controller.js',
                AWS_LAUNCH_INST + 'source/source-help.controller.js',
                AWS_LAUNCH_INST + 'flavor/flavor.controller.js',
                AWS_LAUNCH_INST + 'flavor/select-flavor-table.directive.js',
                AWS_LAUNCH_INST + 'flavor/flavor-help.controller.js',
                AWS_LAUNCH_INST + 'configuration/configuration.controller.js',
                AWS_LAUNCH_INST + 'configuration/configuration-help.controller.js',

                BAREMETAL_LAUNCH_INST + 'launch-instance.js',
                BAREMETAL_LAUNCH_INST + 'launch-instance.model.js',
                BAREMETAL_LAUNCH_INST + 'source/source.controller.js',
                BAREMETAL_LAUNCH_INST + 'source/source-help.controller.js',
                BAREMETAL_LAUNCH_INST + 'flavor/flavor.controller.js',
                BAREMETAL_LAUNCH_INST + 'flavor/flavor-help.controller.js',
                BAREMETAL_LAUNCH_INST + 'network/network.controller.js',
                BAREMETAL_LAUNCH_INST + 'network/network-help.controller.js',
                BAREMETAL_LAUNCH_INST + 'security-groups/security-groups.js',
                BAREMETAL_LAUNCH_INST + 'keypair/keypair.js',
                BAREMETAL_LAUNCH_INST + 'configuration/configuration.controller.js',
                BAREMETAL_LAUNCH_INST + 'networkports/ports.controller.js',
                LAUNCH_INST + 'networkports/ports-help.controller.js',

                'framework/widgets/detail/hzDetailHeader.directive.js',
                'framework/widgets/detail/hzProperty.directive.js',
                'framework/widgets/detail/hzPropertyGroup.directive.js',
                'framework/widgets/detail/hzPropertyGroups.directive.js',
                'framework/widgets/detail/slider.directive.js',

				'lenovo/js/physical_servers/physical_servers.js',
				'lenovo/js/physical_servers/nova.service.js',
				'lenovo/js/physical_servers/action.monitor.js',
				'lenovo/js/physical_servers/index.js',
				'lenovo/js/physical_servers/detail.js',
				'lenovo/js/physical_servers/action.detail.js',
				'lenovo/js/physical_servers/action.js',
				'lenovo/js/physical_servers/server/delete.js',
				'lenovo/js/physical_servers/server/auth.js',

				'lenovo/js/physical_servers/form.js',
				'lenovo/restapi/uus.service.js',
				'lenovo/restapi/switch.service.js',
				'lenovo/restapi/alarm.service.js',
				'lenovo/restapi/overview.service.js',

				#begin:add by jiaozh1
				'dashboard/project/vpn/vpn.js',
				'dashboard/project/vpn/table.js',
				'dashboard/project/vpn/action.edit.js',
				'dashboard/project/vpn/action.create.js',
				'dashboard/project/vpn/action.delete.js',
				'dashboard/project/vpn/form.js',
				'dashboard/project/vpn/action.create.detail.js',
				#end: add by jiaozh1

				'lenovo/js/quickstart/quickstart.js',
				'lenovo/js/quickstart/controller.js',

				'lenovo/js/framework/widgets/magicSearchExt.js',

				'lenovo/js/header/header.module.js',
				'lenovo/js/header/alarm/alarm.js',

				'lenovo/js/network_switches/network_switches.js',
				'lenovo/js/network_switches/index.js',
				'lenovo/js/network_switches/detail.js',
				'lenovo/js/network_switches/action.js',
				'lenovo/js/network_switches/switch/create.js',
				'lenovo/js/network_switches/switch/edit.js',
				'lenovo/js/network_switches/switch/delete.js',
				'lenovo/js/network_switches/detail/create.js',
				'lenovo/js/network_switches/detail/edit.js',
				'lenovo/js/network_switches/detail/delete.js',
				'dashboard/project/topology/horizon.networktopology.js',

                'lenovo/js/ha_management/ha_management.js',
                'lenovo/js/ha_management/index.js',
                'lenovo/js/ha_management/action.edit-ha.js',
                'lenovo/js/ha_management/form.js',

                'lenovo/js/upgrade/upgrade.js',
                'lenovo/js/upgrade/index.js',
                'lenovo/js/upgrade/upgrade/start.js',
                'lenovo/restapi/upgrade.service.js',

    'dashboard/project/server_groups/server_groups.js',
    'dashboard/project/server_groups/table.js',
    'dashboard/project/server_groups/form.js',
    'dashboard/project/server_groups/action.create.js',
    'dashboard/project/server_groups/action.delete.js',
    'dashboard/project/server_groups/action.create.detail.js',

    'dashboard/project/alerts/alerts.js',
    'dashboard/project/alerts/table.js',
    'dashboard/project/alerts/action.create.detail.js',
    'dashboard/project/alerts/form.js',

]
